# Generated by Django 5.1.3 on 2024-11-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_processor', '0002_kpi_assetkpi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetKPI',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
    ]
