# Generated by Django 5.1.3 on 2024-11-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetkpi',
            old_name='kpi',
            new_name='kpi_name',
        ),
    ]
