# Generated by Django 5.1.3 on 2024-11-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_rename_kpi_assetkpi_kpi_name'),
        ('message_processor', '0003_delete_assetkpi_delete_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_processor.message'),
        ),
        migrations.AlterField(
            model_name='assetkpi',
            name='kpi_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpi'),
        ),
    ]
